
export enum BonusModifierType {
  // Ability Scores
  StrengthAbilityChecks = "strength-ability-checks",
  StrengthAttacks = "strength-attacks",
  StrengthSavingThrows = "strength-saving-throws",
  StrengthScore = "strength-score",
  ConstitutionAbilityChecks = "constitution-ability-checks",
  ConstitutionSavingThrows = "consitution-saving-throws",
  ConstitutionScore = "constitution-score",
  DexterityAbilityChecks = "dexterity-ability-checks",
  DexterityAttacks = "dexterity-attacks",
  DexteritySavingThrows = "dexterity-saving-throws",
  DexterityScore = "dexterity-score",
  IntelligenceAbilityChecks = "intelligence-ability-checks",
  IntelligenceSavingThrows = "intelligence-saving-throws",
  IntelligenceScore = "intelligence-score",
  WisdomAbilityChecks = "wisdom-ability-checks",
  WisdomSavingThrows = "wisdom-saving-throws",
  WisdomScore = "wisdom-score",
  CharismaAbilityChecks = "charisma-ability-checks",
  CharismaSavingThrows = "charisma-saving-throws",
  CharismaScore = "charisma-score",
  // Skills
  Acrobatics = "acrobatics",
  AnimalHandling = "animal-handling",
  Arcana = "arcana",
  Athletics = "athletics",
  Deception = "deception",
  History = "history",
  Insight = "insight",
  Intimidation = "intimidation",
  Investigation = "investigation",
  Medicine = "medicine",
  Nature = "nature",
  Perception = "perception",
  Performance = "performance",
  Persuasion = "persuasion",
  Religion = "religion",
  SleightOfHand = "sleight-of-hand",
  Stealth = "stealth",
  Survival = "survival",
  // Stats
  AbilityScoreMaximum = "ability-score-maximum",
  ArmorClass = "armor-class",
  ArmoredArmorClass = "armored-armor-class",
  DualWieldArmorClass = "dual-wield-armor-class",
  HitPoints = "hit-points",
  HitPointsPerLevel = "hit-points-per-level",
  TemporaryHitPoints = "temporary-hit-points",
  Initiative = "initiative",
  PassiveInvestigation = "passive-investigation",
  PassivePerception = "passive-perception",
  PassiveInsight = "passive-insight",
  // Speed
  Speed = "speed",
  SpeedBurrowing = "speed-burrowing",
  SpeedClimbing = "speed-climbing",
  SpeedFlying = "speed-flying",
  SpeedSwimming = "speed-swimming",
  SpeedWalking = "speed-walking",
  // Attacks
  MeleeAttacks = "melee-attacks",
  MeleeReach = "melee-reach",
  MeleeSpellAttacks = "melee-spell-attacks",
  MeleeWeaponAttacks = "melee-weapon-attacks",
  RangedAttacks = "ranged-attacks",
  RangedSpellAttacks = "ranged-spell-attacks",
  RangedWeaponAttacks = "ranged-weapon-attacks",
  NaturalAttacks = "natural-attacks",
  ExtraAttacks = "extra-attacks",
  // Spells
  SpellAttackRangeMultiplier = "spell-attack-range-multiplier",
  SpellAttacks = "spell-attacks",
  SpellSaveDC = "spell-save-dc",
  // Unarmed
  UnarmedAttacks = "unarmed-attacks",
  UnarmoredArmorClass = "unarmored-armor-class",
  UnarmoredMovement = "unarmored-movement",
  // Proficiency
  Proficiency = "proficiency",
  HalfProficiency = "half-proficiency",
  ProficiencyBonus = "proficiency-bonus",
  TwiceProficiencyBonus = "twice-proficiency-bonus",
  // Choose Ability Scores
  ChooseAnAbilityScore = "choose-an-ability-score",
  ChooseConstitutionOrIntelligence = "choose-constitution-or-intelligence",   // TODO: Can all this be condensed?
  ChooseConstitutionOrWisdom = "choose-constitution-or-wisdom",
  ChooseDexterityOrCharisma = "choose-dexterity-or-charisma",
  ChooseDexterityOrConstitution = "choose-dexterity-or-constitution",
  ChooseDexterityOrIntelligence = "choose-dexterity-or-intelligence",
  ChooseDexterityOrWisdom = "choose-dexterity-or-wisdom",
  ChooseDexterityConstitutionOrCharisma = "choose-dexterity-constitution-or-charisma",
  ChooseDexterityIntelligenceWisdomOrCharisma = "choose-dexterity-intelligence-wisdom-or-charisma",
  ChooseIntelligenceOrCharisma = "choose-intelligence-or-charisma",
  ChooseIntelligenceOrWisdom = "choose-intelligence-or-wisdom",
  ChooseStrengthOrConstitution = "choose-strength-or-constitution",
  ChooseStrengthOrDexterity = "choose-strength-or-dexterity",
  ChooseStrengthOrWisdom = "choose-strength-or-wisdom",
  ChooseStrengthConstitutionOrCharisma = "choose-strength-constitution-or-charisma",
  ChooseStrengthConstitutionOrDexterity = "choose-strength-constitution-or-dexterity",
  ChooseStrengthDexterityOrWisdom = "choose-strength-dexterity-or-wisdom",
  // Checks
  AbilityChecks = "ability-checks",
  SavingThrows = "saving-throws",
  // Other
  ACMaxDexModifier = "ac-max-dex-modifier",
  ClericCantripDamage = "cleric-cantrip-damage",
  EldritchBlastDamage = "eldritch-blast-damage",
  DomainSpell = "domain-spell",
  Magic = "magic",
  ShieldACOnDexSaves = "shield-ac-on-dex-saves",
  WeaponAttackRangeMultiplier = "weapon-attack-range-multiplier",
}

// Ability Checks,
// Ability Score Maximum,
// AC Max Dex Modifier,
// Acrobatics,
// Animal Handling,
// Arcana,
// Armor Class,
// Armored Armor Class,
// Athletics,
// Charisma Ability Checks,
// Charisma Saving Throws,
// Charisma Score,
// Choose an Ability Score,
// Choose Constitution or Intelligence,
// Choose Constitution or Wisdom,
// Choose Dexterity or Charisma,
// Choose Dexterity or Constitution,
// Choose Dexterity or Intelligence,
// Choose Dexterity or Wisdom,
// Choose Dexterity, Constitution, or Charisma,
// Choose Dexterity, Intelligence, Wisdom, or Charisma,
// Choose Intelligence or Charisma,
// Choose Intelligence or Wisdom,
// Choose Strength or Constitution,
// Choose Strength or Dexterity,
// Choose Strength or Wisdom,
// Choose Strength, Constitution, or Charisma,
// Choose Strength, Constitution, or Dexterity,
// Choose Strength, Dexterity, or Wisdom ,
// Cleric Cantrip Damage,
// Constitution Ability Checks,
// Constitution Saving Throws,
// Constitution Score,
// Deception,
// Dexterity Ability Checks,
// Dexterity Attacks,
// Dexterity Saving Throws,
// Dexterity Score,
// Domain Spell,
// Dual Wield Armor Class,
// Eldritch Blast Damage,
// Extra Attacks,
// Half Proficiency,
// History,
// Hit Points,
// Hit Points per Level,
// Initiative,
// Insight,
// Intelligence Ability Checks,
// Intelligence Saving Throws,
// Intelligence Score,
// Intimidation,
// Investigation,
// Magic,
// Medicine,
// Melee Attacks,
// Melee Reach,
// Melee Spell Attacks,
// Melee Weapon Attacks,
// Natural Attacks,
// Nature,
// Passive Investigation,
// Passive Perception,
// Perception,
// Performance,
// Persuasion,
// Proficiency,
// Proficiency Bonus,
// Ranged Attacks,
// Ranged Spell Attacks,
// Ranged Weapon Attacks,
// Religion,
// Saving Throws,
// Shield AC on Dex Saves,
// Sleight of Hand,
// Speed,
// Speed (Burrowing),
// Speed (Climbing),
// Speed (Flying),
// Speed (Swimming),
// Speed (Walking),
// Spell Attack Range Multiplier,
// Spell Attacks,
// Spell Save DC,
// Stealth,
// Strength Ability Checks,
// Strength Attacks,
// Strength Saving Throws,
// Strength Score,
// Survival,
// Temporary Hit Points,
// Twice Proficiency Bonus,
// Unarmed Attacks,
// Unarmored Armor Class,
// Unarmored Movement,
// Weapon Attack Range Multiplier,
// Wisdom Ability Checks,
// Wisdom Saving Throws,
// Wisdom Score,
