
export enum CreatureTypes {
  Aberrations = 'aberrations',
  Beasts = 'beasts',
  Celestials = 'celestials',
  Constructs = 'constructs',
  Dragonborn = 'dragonborn',
  Dragons = 'dragons',
  Dwarves = 'dwarves',
  Elementals = 'elementals',
  Elves = 'elves',
  Fey = 'fey',
  Fiends = 'fiends',
  Giants = 'giants',
  Gnolls = 'gnolls',
  Gnomes = 'gnomes',
  Goblinoids = 'goblinoids',
  Grimlock = 'grimlock',
  Halflings = 'halflings',
  Humans = 'humans',
  Kobolds = 'kobolds',
  Lizardfolk = 'lizardfolk',
  Merfolk = 'merfolk',
  Monstrosities = 'monstrosities',
  Oozes = 'oozes',
  Orcs = 'orcs',
  Plants = 'plants',
  Sahuagin = 'sahuagin',
  Undead = 'undead',
  Werebears = 'werebears',
  Wereboars = 'wereboars',
  Wererats = 'wererats',
  Werewolves = 'werewolves',
}
