
export enum DamageModifierSubType {
  // Damage Type
  All = "all",
  Acid = "acid",
  Bludgeoning = "bludgeoning",
  Cold = "cold",
  Fire = "fire",
  Force = "force",
  Lightning = "lightning",
  Necrotic = "necrotic",
  Piercing = "piercing",
  Poison = "poison",
  Psychic = "psychic",
  Radiant = "radiant",
  Slashing = "slashing",
  Thunder = "thunder",
  PhysicalDamageFromNonmagicWeapons = "physical-damage-from-nonmagic-weapons",
  TrapDamage = "trap-damage",
  // Attack Type
  Shortbow = "shortbow",
  Longbow = "longbow",
  MeleeAttacks = "melee-attacks",
  MeleeSpellAttacks = "melee-spell-attacks",
  MeleeWeaponAttacks = "melee-weapon-attacks",
  RangedAttacks = "ranged-attacks",
  RangedSpellAttacks = "ranged-spell-attacks",
  RangedWeaponAttacks = "ranged-weapon-attacks",
  OneHandedMeleeAttacks = "one-handed-melee-attacks",
  TwoHandedMeleeAttacks = "two-handed-melee-attacks",
  UnarmedAttacks = "unarmed-attacks",
  NaturalAttacks = "natural-attacks",
}
