
export enum Tags {
  Buff = "buff",
  Combat = "combat",
  Communication = "communication",
  Component = "component",
  Consumable = "consumable",
  Container = "container",
  Control = "control",
  Damage = "damage",
  Debuff = "debuff",
  Deception = "deception",
  Detection = "detection",
  Exploration = "exploration",
  Healing = "healing",
  Instrument = "instrument",
  Movement = "movement",
  Outerwear = "outerwear",
  Social = "social",
  Utility = "utility",
  Warding = "warding",
  Guild = 'guild',
  Monstrous = 'monstrous',
  RacialFeat = 'racial-feat',
  Religious = 'religious',
}
